import {WorldCopy} from './WorldCopy';
import { useState, useEffect, useRef } from 'react';
import { ArrowLeft, ArrowRight, CaretLeft, CaretRight, X, List, ThumbsUp, IdentificationCard, PersonSimple, Coffee, Key, Rabbit, PersonArmsSpread, Shield, Sticker, Magnet, Notepad, Play, ArrowUpRight } from '@phosphor-icons/react';
import { worlds, categories, links } from './content';
import { media } from './media';
import {Characters, NovelShelf} from './Shelves';
import {GoodsCarousel} from './GoodsCarousel';
import {WorldMedia, WorldThumbnail, MoviePosters, GoodsMascot, MascotSpeech} from './MediaDisplays';
import {acceptAnalytics, declineAnalytics, enterPage, getAnalyticsConsent, isAnalyticsEnabled, trackInternalNavigation} from './analytics';
const sections = ['메인','세계관','등장인물','웹소설','영화','굿즈'];
const ids = ['main','world','characters','novel','movie','goods'];
const icons = [IdentificationCard,PersonSimple,Coffee,Key,Rabbit,PersonArmsSpread,Shield,Sticker,Magnet,Notepad];
function External({href,children,...props}) { return <a href={href} target="_blank" rel="noreferrer" {...props}>{children}</a>; }
function Media({src,label,className=''}) { return <div className={`media ${className}`} aria-label={label}>{src?<img src={src} alt={label}/>:<span className="media-label">{label}</span>}</div>; }
function Brand(){return media.logo?<img className="brand-image" src={media.logo} alt="전지적 독자 시점"/>:<span className="brand-type">전지적<span>독자시점</span></span>;}
function AnalyticsConsent(){const [choice,setChoice]=useState(()=>getAnalyticsConsent());if(!isAnalyticsEnabled()||choice)return null;return <aside className="analytics-consent" aria-label="분석 쿠키 설정"><p><strong>방문 분석 안내</strong><span>사이트 이용 흐름을 개선하기 위해 익명 이용 기록을 수집합니다. 개인정보와 IP 주소는 수집하지 않습니다.</span></p><div><button onClick={()=>{declineAnalytics();setChoice('denied')}}>거부</button><button className="accept" onClick={()=>{acceptAnalytics();setChoice('granted')}}>동의</button></div></aside>}
function Pager({page,setPage,total}){return <div className="pager"><button aria-label="이전 내용" disabled={page===0} onClick={()=>setPage(page-1)}><ArrowLeft/></button><span>{page+1} / {total}</span><button aria-label="다음 내용" disabled={page===total-1} onClick={()=>setPage(page+1)}><ArrowRight/></button></div>;}
function Modal({title,onClose,children}){const ref=useRef(null);useEffect(()=>{const el=ref.current;el.showModal();return()=>el.close();},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label={title}><div className="modal-head"><h2>{title}</h2><button onClick={onClose} aria-label="닫기" autoFocus><X/></button></div>{children}</dialog>;}
export function App(){
 const [active,setActive]=useState(ids.includes(location.hash.slice(1))?location.hash.slice(1):'main');
 const [menu,setMenu]=useState(false);const [world,setWorld]=useState(0);const [page,setPage]=useState(0);
 const [more,setMore]=useState(false);
 const [trailer,setTrailer]=useState(null);const [category,setCategory]=useState(0);
 const scrollRef=useRef(null);const lock=useRef(false);
 const go=(id,method='unknown')=>{trackInternalNavigation(active,id,method);setActive(id);setMenu(false);history.pushState(null,'',`#${id}`);scrollRef.current?.scrollTo({top:0});};
 useEffect(()=>{enterPage(active);},[active]);
 useEffect(()=>{const fn=()=>{const next=ids.includes(location.hash.slice(1))?location.hash.slice(1):'main';setActive(previous=>{trackInternalNavigation(previous,next,'browser_history');return next;});setMenu(false);};window.addEventListener('popstate',fn);return()=>window.removeEventListener('popstate',fn);},[]);
 useEffect(()=>{const el=scrollRef.current;let sum=0;let timer;const wheel=e=>{if(document.querySelector('dialog[open]')||e.ctrlKey||Math.abs(e.deltaX)>Math.abs(e.deltaY))return;let node=e.target;while(node&&node!==el){const style=getComputedStyle(node);if(/auto|scroll/.test(style.overflowY)&&node.scrollHeight>node.clientHeight+2){const room=e.deltaY>0?node.scrollTop+node.clientHeight<node.scrollHeight-2:node.scrollTop>0;if(room)return;}node=node.parentElement;}const canScroll=el.scrollHeight>el.clientHeight+2;const edge=e.deltaY>0?el.scrollTop+el.clientHeight>=el.scrollHeight-2:el.scrollTop<=0;if(canScroll&&!edge)return;sum+=e.deltaY;clearTimeout(timer);timer=setTimeout(()=>sum=0,180);if(Math.abs(sum)<65||lock.current)return;const next=ids.indexOf(active)+(sum>0?1:-1);if(next>=0&&next<ids.length){e.preventDefault();lock.current=true;go(ids[next]);setTimeout(()=>lock.current=false,850);}sum=0;};let touch=null;const touchStart=e=>{touch={x:e.touches[0].clientX,y:e.touches[0].clientY,top:el.scrollTop}};const touchEnd=e=>{if(!touch)return;const dy=touch.y-e.changedTouches[0].clientY,dx=touch.x-e.changedTouches[0].clientX;const edge=dy>0?touch.top+el.clientHeight>=el.scrollHeight-2:touch.top<=0;if(edge&&Math.abs(dy)>65&&Math.abs(dy)>Math.abs(dx))wheel({target:e.target,deltaY:dy,deltaX:dx,preventDefault:()=>{}});touch=null};el.addEventListener('wheel',wheel,{passive:false});el.addEventListener('touchstart',touchStart,{passive:true});el.addEventListener('touchend',touchEnd,{passive:true});return()=>{el.removeEventListener('wheel',wheel);el.removeEventListener('touchstart',touchStart);el.removeEventListener('touchend',touchEnd);clearTimeout(timer);};},[active]);
 useEffect(()=>{const key=e=>{if(e.key==='Escape'){setMenu(false);setTrailer(null);}if(e.target.closest('button,a,input,dialog,select,textarea'))return;let next=ids.indexOf(active);if(e.key==='PageDown')next++;else if(e.key==='PageUp')next--;else return;e.preventDefault();if(ids[next])go(ids[next]);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[active]);
 const currentWorld=worlds[world];
 return <><a className="skip" href="#content">본문으로 이동</a><header className="header"><a href="#main" onClick={e=>{e.preventDefault();go('main');}} className="brand" aria-label="전지적 독자 시점 메인"><Brand/></a><nav aria-label="주 메뉴" className={menu?'open':''}>{sections.map((s,i)=><a key={s} href={`#${ids[i]}`} className={active===ids[i]?'active':''} aria-current={active===ids[i]?'page':undefined} onClick={e=>{e.preventDefault();go(ids[i]);}}>{s}</a>)}</nav><External className="webtoon-link" href={links.webtoon}>웹툰 바로가기</External><button className="menu-toggle" aria-label={menu?'메뉴 닫기':'메뉴 열기'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<List/>}</button></header>
 <main id="content" ref={scrollRef} tabIndex={-1} className={`viewport screen-${active}`}><div className="screen" key={active}>
 {active==='main'&&<section className="hero" aria-label="메인"><h1 className="sr-only">전지적 독자 시점</h1>{media.heroVideo?<video src={media.heroVideo} poster={media.heroPoster||undefined} autoPlay loop muted playsInline controls/>:<Media src={media.heroPoster} label="메인 영상 영역" className="hero-media"/>}<div className="scroll-cue" aria-label="아래로 스크롤"><span>SCROLL</span><i aria-hidden="true"/></div></section>}
 {active==='world'&&<section className="world-layout" aria-label="세계관"><div className="world-visual"><WorldMedia index={world} name={currentWorld.name}/><h1 key={world}>{currentWorld.title}</h1><div className="world-tabs" aria-label="세계관 주제">{worlds.map((w,i)=><button key={w.name} aria-label={w.name} title={w.name} aria-pressed={world===i} className={world===i?'selected':''} onClick={()=>{setWorld(i);setPage(0);}}><WorldThumbnail index={i}/></button>)}</div></div><WorldCopy key={world} world={currentWorld}/><aside className="world-quote"><span className="quote-mark">“</span><p className="quote-caption">— {world===0?'멸살법 마지막 문장':'세계관 소개'}</p><blockquote key={world}>{currentWorld.quote}</blockquote><span className="quote-mark end">”</span></aside></section>}
 {active==='characters'&&<Characters/>}
 {active==='novel'&&<NovelShelf/>}
 {active==='movie'&&<section className={`movie-section ${trailer!==null?'watching':''}`} aria-label="영화">{trailer===null?<><MoviePosters/><div className="movie-actions"><button className="outline-button" onClick={()=>setTrailer(0)}>예고편 보기</button><External className="outline-button" href={links.movie}>영화 바로가기</External></div></>:<><aside className="trailer-list">{['메인 예고편','런칭 예고편','영화 소개'].map((s,i)=><button key={s} onClick={()=>setTrailer(i)} className={trailer===i?'selected':''}><Play/><span>{s}</span></button>)}</aside><div className="trailer-content"><h1>{['메인 예고편','런칭 예고편','영화 소개'][trailer]}</h1>{media.trailers[trailer]?<video key={trailer} src={media.trailers[trailer]} controls autoPlay playsInline/>:<div className="trailer-empty"><Play size={38}/><p>{trailer===2?'소설의 결말을 바꾸기 위한 김독자와 동료들의 여정.':'예고편 영상 영역'}</p><External className="outline-button" href={trailer===1?'https://www.youtube.com/watch?v=YRIW33DftIM':trailer===2?links.movie:links.trailer}>{trailer===2?'영화 정보 보기':'공식 예고편 보기'} <ArrowUpRight/></External></div>}<p className="film-caption">전지적 독자 시점 · 2025 · 감독 김병우<br/>안효섭 · 이민호 · 채수빈 · 신승호 · 나나 · 지수</p></div><button className="poster-return outline-button" onClick={()=>setTrailer(null)}>포스터로 돌아가기</button></>}</section>}
 {active==='goods'&&<section className="goods-section" aria-label="굿즈"><div className="goods-main"><div className="mascot-area"><MascotSpeech/><GoodsMascot/></div><div className="goods-panel"><i className="panel-corner tl"/><i className="panel-corner tr"/><i className="panel-corner bl"/><i className="panel-corner br"/><h1>도깨비 보따리</h1><GoodsCarousel categoryIndex={category} onCategoryChange={setCategory}/><div className="goods-controls"><div className="category-grid">{categories.map((c,i)=>{const Icon=icons[i];return <button key={c} aria-pressed={category===i} className={category===i?'selected':''} onClick={()=>{setCategory(i);}}><Icon/><span>{c}</span></button>;})}</div><External className="goods-more" href={links.store}>더 보러가기</External></div></div></div><footer><Brand/><span>© Omniscient Reader’s Viewpoint <small>팬 메이드 사이트</small></span><div><External href={links.novel} aria-label="네이버 시리즈">SERIES</External><External href={links.webtoon} aria-label="네이버 웹툰">WEBTOON</External><button onClick={()=>setMore('sources')}>출처</button></div></footer></section>}
 </div></main>
 {more==='sources'&&<Modal title="작품 정보 및 출처" onClose={()=>setMore(false)}><div className="source-content"><p>전지적 독자 시점 · 원작 싱숑<br/>웹툰 각색 UMI · 그림 슬리피-C</p><p>작품 소개와 세계관 설명은 아래 자료를 참고해 요약했습니다. 단행본 목차는 출판사 제공 도서 정보를 참고했습니다.</p>{Object.entries({webtoon:'네이버 웹툰',novel:'네이버 시리즈',books:'단행본',movie:'영화 정보',trailer:'롯데엔터테인먼트 공식 예고편',store:'스타스트림 스토어'}).map(([k,v])=><External key={k} href={links[k]}>{v} <ArrowUpRight/></External>)}<p>팬 메이드 구현입니다. 작품과 미디어의 권리는 각 권리자에게 있습니다.</p></div></Modal>}
 <AnalyticsConsent/>
 </>;
}
