import {useState,useRef,useEffect} from 'react';
import {ArrowLeft,ArrowRight,X} from '@phosphor-icons/react';
import {books,characters,links} from './content';
import {media} from './media';
import {contents,firstExcerpt,partIntros} from './bookDetails';
import {catalog,characterGroups} from './characterCatalog';
export function MediaSlot({src,label,className=''}){return <div className={`media ${className}`} aria-label={label}>{src?<img src={src} alt={label}/>:<span className="media-label">{label}</span>}</div>}
function useShelf(items,selected,preservePosition=false){
 const ref=useRef(null);const [edges,setEdges]=useState({start:true,end:true});
 useEffect(()=>{const el=ref.current;if(!el)return;const update=()=>setEdges({start:el.scrollLeft<2,end:el.scrollLeft+el.clientWidth>=el.scrollWidth-2});if(!preservePosition)el.scrollLeft=0;update();const observer=new ResizeObserver(update);observer.observe(el);el.addEventListener('scroll',update);return()=>{observer.disconnect();el.removeEventListener('scroll',update);}},[items,selected,preservePosition]);
 useEffect(()=>{if(!selected)return;const el=ref.current;if(!el)return;const frame=requestAnimationFrame(()=>{const item=el.querySelector('.inline-book-open, .inline-person-open');if(!item)return;const box=item.getBoundingClientRect(),viewport=el.getBoundingClientRect();if(box.left<viewport.left||box.right>viewport.right){el.scrollTo({left:el.scrollLeft+box.left-viewport.left,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}});return()=>cancelAnimationFrame(frame)},[selected]);
 const move=d=>ref.current?.scrollBy({left:d*Math.max(100,ref.current.clientWidth*.75),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
 return {ref,edges,move};
}
function ShelfArrows({edges,move,label}){return <div className="shelf-arrows"><button aria-label={`이전 ${label}`} disabled={edges.start} onClick={()=>move(-1)}><ArrowLeft/></button><button aria-label={`다음 ${label}`} disabled={edges.end} onClick={()=>move(1)}><ArrowRight/></button></div>}
function BookSpine({b,selected,onClick}){if(media.bookSpines[b.id])return <button className="book-spine image-spine" aria-label={`Part ${b.part} ${b.volume}권 상세 보기`} aria-expanded={selected} onClick={onClick}><img src={media.bookSpines[b.id]} alt={`Part ${b.part} ${b.volume}권 책등`}/></button>;return <button className="book-spine" aria-label={`Part ${b.part} ${b.volume}권 상세 보기`} aria-expanded={selected} onClick={onClick}><span className="spine-title">전지적 독자 시점</span><span className="spine-english">Omniscient<br/>Reader’s<br/>Viewpoint</span><span className="spine-part">PART {b.part}</span><strong>{String(b.volume).padStart(2,'0')}</strong><span className="spine-author">싱숑 장편소설</span><span className="spine-publisher">비채</span></button>}
export function NovelShelf(){
 const [part,setPart]=useState(0);const [selected,setSelected]=useState(null);
 const {ref,edges,move}=useShelf(part,selected?.id,true);
 useEffect(()=>{const close=e=>{if(e.key==='Escape')setSelected(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 const visible=books.filter(b=>!part||b.part===part);
 const close=()=>{const id=selected?.id;setSelected(null);requestAnimationFrame(()=>document.querySelector(`[data-book-id="${id}"] button`)?.focus({preventScroll:true}))};
 return <section className={`shelf-layout novel-shelf ${selected?'detail-open':''}`} aria-label="웹소설"><aside className="shelf-filter">{['ALL','Part 1','Part 2','Part 3','Part 4','Part 5'].map((p,i)=><button key={p} aria-pressed={part===i} className={part===i?'selected':''} onClick={()=>{setPart(i);setSelected(null);ref.current?.scrollTo({left:0})}}>{p}</button>)}</aside><div className="shelf-content"><h1 className="sr-only">전지적 독자 시점 웹소설 단행본</h1><div className="shelf-stage">
 <div className="spine-scroll inline-book-scroll" ref={ref} data-inner-scroll aria-label="책등 목록" tabIndex={0}>{visible.map(b=><div className={`spine-item ${media.bookSpines[b.id]?'has-spine-image':''} ${selected?.id===b.id?'inline-book-open':''}`} key={b.id} data-book-id={b.id}><BookSpine b={b} selected={selected?.id===b.id} onClick={()=>selected?.id===b.id?close():setSelected(b)}/>{selected?.id===b.id?<article className="novel-detail" aria-label={`Part ${b.part} ${b.volume}권 상세`}><MediaSlot src={media.bookCovers[b.id]} label={`Part ${b.part} ${b.volume}권 표지 영역`} className="detail-cover"/><div className="novel-detail-copy"><button className="detail-close" onClick={close} aria-label="책 상세 닫기"><X/></button><div className="excerpt-panel"><p>{b.id==='1-1'?firstExcerpt:partIntros[b.part]}</p><span>{b.id==='1-1'?'— Episode 01. 유료 서비스 돌입 中 —':`— Part ${b.part} 내용 소개 · 요약 —`}</span></div><ol className="chapter-list" aria-label="목차">{contents[b.id].map((c,i)=><li key={`${c.label}-${i}`} className={c.label==='Prologue'?'prologue':!c.title?'afterword':''}><span>{c.label}</span><p>{c.title}</p></li>)}</ol><a className="outline-button novel-link" href={links.books} target="_blank" rel="noreferrer">웹소설 바로가기</a></div></article>:<div className="spine-preview" aria-hidden="true"><MediaSlot src={media.bookCovers[b.id]} label={`Part ${b.part} ${b.volume}권 표지 영역`}/></div>}</div>)}</div></div><div className="shelf-bottom"><ShelfArrows edges={edges} move={move} label="책등"/></div></div></section>
}
function CharacterInfo({c,onClose}){return <div className="person-detail"><button className="detail-close" aria-label="인물 상세 닫기" onClick={onClose}><X/></button><span className="eyebrow">{c.en}</span><h1>{c.name}</h1><h2>{c.role}</h2><p>{c.desc}</p><dl><dt>분류</dt><dd>{c.group||'김독자 일행'}</dd><dt>키워드</dt><dd>{c.tags.join(' · ')}</dd></dl></div>}
export function Characters(){
 const [selected,setSelected]=useState(null);const [library,setLibrary]=useState(false);const [group,setGroup]=useState(0);const [person,setPerson]=useState(null);
 const {ref,edges,move}=useShelf(`${library}-${group}`,person?.id,true);
 useEffect(()=>{const close=e=>{if(e.key==='Escape'){setSelected(null);setPerson(null)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 if(library)return <section className={`shelf-layout character-library ${person?'person-open':''}`} aria-label="등장인물 전체보기"><aside className="shelf-filter character-filter">{characterGroups.map((g,i)=><button key={g} className={group===i?'selected':''} aria-pressed={group===i} onClick={()=>{setGroup(i);setPerson(null);ref.current?.scrollTo({left:0})}}>{g}</button>)}<button className="character-overview" onClick={()=>setLibrary(false)}>주요 인물 <ArrowLeft/></button></aside><div className="shelf-content"><div className="shelf-stage"><div ref={ref} className="spine-scroll character-spine-scroll" data-inner-scroll tabIndex={0} aria-label="인물 목록">{catalog.filter(c=>!group||c.group===characterGroups[group]).map(c=><div key={c.id} className={`character-shelf-item ${person?.id===c.id?'inline-person-open':''}`}><button className={`character-spine ${person?.id===c.id?'selected':''}`} aria-expanded={person?.id===c.id} aria-label={`${c.group} · ${c.role ? c.role + ' · ' : ''}${c.name} 상세 보기`} title={`${c.role ? c.role + ' · ' : ''}${c.name}`} onClick={()=>setPerson(person?.id===c.id?null:c)}><MediaSlot src={media.characterCatalog?.[c.id] || media.characters[c.mediaIndex]} label={`${c.name} 이미지 영역`}/>{c.role&&<small className="catalog-role">{c.role}</small>}<span>{c.name}</span></button>{person?.id===c.id&&<article className="library-detail"><MediaSlot src={media.characterCatalog?.[c.id] || media.characters[c.mediaIndex]} label={`${c.name} 이미지 영역`}/><CharacterInfo c={c} onClose={()=>setPerson(null)}/></article>}</div>)}</div></div><div className="shelf-bottom"><span className="catalog-caption">{characterGroups[group]}</span><ShelfArrows edges={edges} move={move} label="인물"/></div></div></section>;
 return <section className={`people-section ${selected!==null?'is-expanded':''}`} aria-label="등장인물"><div className="people-stage"><MediaSlot src={media.characterLogo} label="작품 로고 영역" className="people-logo"/>{characters.slice(0,5).map((c,i)=><div key={c.name} className={`people-unit ${selected===i?'selected':''}`}><button className="people-portrait" aria-label={`${c.name} 소개`} aria-expanded={selected===i} onClick={()=>setSelected(selected===i?null:i)}><MediaSlot src={media.characters[i]} label={`${c.name} 이미지 영역`}/><span>{c.name}</span></button>{selected===i&&<CharacterInfo c={catalog.find(person=>person.group==='김독자 컴퍼니'&&person.name===c.name)} onClose={()=>setSelected(null)}/>}</div>)}</div><div className="section-bottom"><button onClick={()=>{setLibrary(true);setSelected(null)}}>등장인물 더 보기 <ArrowRight/></button></div></section>
}
